apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: hoang1712/nginx:v1.0.0 # {"$imagepolicy": "flux-system:helloworld"}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"