---

- hosts: masters, workers
  name: Setup masters and workers
  remote_user: aen
  become: true
  tasks:
   # Disable swap to start kubelet
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Load overlay module
      shell: modprobe overlay
    - name: Load br_netfilter module
      shell: modprobe br_netfilter

    - name: Configure two above module
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
        overlay
        br_netfilter
        EOF

    - name: Configure iptables to see bridged traffic
      shell: |
        cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        EOF

    - name: Read values from all system directories
      shell: sysctl --system

    # https://docs.docker.com/engine/install/ubuntu/#installation-methods
    # - name: Install packages to allow apt to use a repository over HTTPS
    #   apt:
    #     name:
    #       - ca-certificates
    #       - gnupg
    #       - apt-transport-https
    #     state: present
    #     update_cache: yes

    # https://kubernetes.io/docs/setup/production-environment/container-runtimes/
    - name: Install containerd
      apt:
        name: containerd
        state: present
        update_cache: yes

    - name: Create containerd configuration folder
      file: 
        path: /etc/containerd
        state: directory
        owner: aen
        group: aen
        mode: 0755

    - name: Create configuration file
      shell: sudo containerd config default | sudo tee /etc/containerd/config.toml
    
    - name: Add plugin containerd cri
      blockinfile:
        path: /etc/containerd/config.toml
        block: |
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]

    - name: Change systemdCgroup
      shell: sudo sed -i 's/            SystemdCgroup = false/            SystemdCgroup = true/' /etc/containerd/config.toml

    - name: Reload containerd
      service:
        name: containerd
        daemon_reload: yes
        enabled: yes

    - name: Create kubelet folder
      file: 
        path: /var/lib/kubelet
        state: directory
        owner: aen
        group: aen
        mode: 0755

    - name: Add Google Cloud public signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes
        mode: 0600

    - name: Install kubelet, kubeadm and kubectl
      apt:
        name:
          - kubeadm=1.23.1-00
          - kubectl=1.23.1-00
          - kubelet=1.23.1-00
        state: present
        update_cache: yes

    - name: Enable kubelet service
      service:
        name: kubelet
        daemon_reload: yes
        enabled: yes

- hosts: masters
  name: Init cluster
  remote_user: aen
  become: true
  tasks:
    - name: Reset existing cluster
      shell: kubeadm reset -f

    - name: Remove .kube in user home directory
      shell: rm -rf .kube

    - name: Remove /etc/kubernetes/manifests directory
      shell: rm -rf /etc/kubernetes/manifests

    - name: Remove /var/lib/etcd directory
      shell: rm -rf /var/lib/etcd

    - name: Init kubernetes cluster
      shell: kubeadm init --control-plane-endpoint=192.168.56.200:6443 --upload-certs --apiserver-advertise-address=192.168.56.200 --pod-network-cidr=192.168.0.0/16

    # This got updated after the video
    # Use release 0.16.3, rather than master version!
    # - name: Copy kube-flannel-v0.16.3.yml
    #   copy:
    #     src: ../kube-flannel-v0.16.3.yml
    #     dest: /home/aen/kube-flannel-v0.16.3.yml
    #     owner: aen
    #     group: aen
    #     mode: '0644'

    # - name: Deploy Flannel network
    #   shell: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f kube-flannel-v0.16.3.yml

    - name: Install calico pod network
      become: true
      become_user: root
      command: kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f https://docs.projectcalico.org/manifests/calico.yaml

    - name: Print join command
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Copy join command to local
      become: false
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

    - name: Create directory for kube config
      file:
        path: /home/aen/.kube
        state: directory
        owner: aen
        group: aen
        mode: 0755

    - name: Copy /etc/kubernetes/admin.conf to user home directory
      become_user: root
      become_method: sudo
      become: true
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/aen/.kube/config
        remote_src: yes
        owner: aen
        group: aen
        mode: '0644'

    # This got updated after the video
    # Because of https://github.com/kubernetes/kubernetes/issues/60835#issuecomment-395931644
    - name: Edit kubeadm.conf
      blockinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        block: |
          Environment="KUBELET_EXTRA_ARGS=--node-ip={{ inventory_hostname }}"

    - name: Restart kubelet service
      service:
        name: kubelet
        daemon-reload: yes
        state: restarted

- hosts: workers
  name: Join workers
  remote_user: aen
  become: true
  tasks:
    - name: Reset existing cluster
      shell: kubeadm reset -f

    - name: Remove .kube in user home directory
      shell: rm -rf .kube

    - name: Remove /etc/kubernetes/manifests directory
      shell: rm -rf /etc/kubernetes/manifests

    - name: Copy join command to workers
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Execute worker join command
      shell: sh /tmp/kubernetes_join_command

    # This got updated after the video
    # Because of https://github.com/kubernetes/kubernetes/issues/60835#issuecomment-395931644
    - name: Edit kubeadm.conf
      blockinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        block: |
          Environment="KUBELET_EXTRA_ARGS=--node-ip={{ inventory_hostname }}"

    - name: Restart kubelet service
      service:
        name: kubelet
        daemon-reload: yes
        state: restarted
