Vagrant.configure("2") do |config|

    # Master Nodes
    MasterCount = 1
    (1..MasterCount).each do |i|
        config.vm.define "k8s-master-#{i}" do |master|
            master.vm.box = "ubuntu/focal64"
            master.vm.hostname = "k8s-master-#{i}"
            master.vm.network "private_network", ip: "192.168.56.#{199 + i}"

            master.vm.provider "virtualbox" do |vb|
                vb.name = "k8s-master-#{i}"
                vb.memory = 2048
                vb.cpus = 2
            end
        end
    end

    # Worker Nodes
    WorkerCount = 2
    (1..WorkerCount).each do |i|
        config.vm.define "k8s-worker-#{i}" do |worker|
            worker.vm.box = "ubuntu/focal64"
            worker.vm.hostname = "k8s-worker-#{i}"
            worker.vm.network "private_network", ip: "192.168.56.20#{i}"

            worker.vm.provider "virtualbox" do |vb|
                vb.name = "k8s-worker-#{i}"
                vb.memory = 2048
                vb.cpus = 2
            end
        end
    end

    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
            # Create aen user
            useradd -s /bin/bash -d /home/aen/ -m -G sudo aen
            echo 'aen ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
            mkdir -p /home/aen/.ssh && chown -R aen /home/aen/.ssh
            echo #{ssh_pub_key} >> /home/aen/.ssh/authorized_keys
        SHELL
    end

end
